name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: mac
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        make bin/lc
        cd bin && tar -zcvf ../${{ matrix.name }}.tar.gz lc && cd -
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        prerelease: true
        artifacts: ${{ matrix.name }}.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}